### ISSUE TITLE
minsdk 18 why?

### ISSUE THREAD

**Issue by sirvon** [RadiusNetworks/proximitykit-android#4]
this lib went from extremely promising to retardedly fustrating....

why use minsdk 18?

Error:(38, 5) Execution failed for task ':app:processLoqooappsSINGLEDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 18 declared in library /home/creator/AndroidStudioProjects/loqooapps/app/build/intermediates/exploded-aar/com.radiusnetworks/proximitykit-android/0.2.0/AndroidManifest.xml
  	Suggestion: use tools:overrideLibrary="com.radiusnetworks.proximity" to force usage

this designation doesn't work for me 
```xml
<uses-sdk tools:overrideLibrary="com.radiusnetworks.proximity" />
```
what gives?

**Comment by cupakromer** [comment]
This is now available in the latest release [0.3.0](https://github.com/RadiusNetworks/proximitykit-android/releases/tag/0.3.0)
