### ISSUE TITLE
Any thoughts on battery life

### ISSUE THREAD

**Issue by pnetesa** [RadiusNetworks/proximitykit-android#5]
Hi guys

Users report too mush usage of battery. Applying this [recommendations](http://altbeacon.github.io/android-beacon-library/battery_manager.html) makes no help as you already utilize BackgroundPowerSaver in your BeaconAdapter class and the default values for scan periods 

  DEFAULT_FOREGROUND_SCAN_PERIOD = 1100L;
  DEFAULT_FOREGROUND_BETWEEN_SCAN_PERIOD = 0L;
  DEFAULT_BACKGROUND_SCAN_PERIOD = 10000L;
  DEFAULT_BACKGROUND_BETWEEN_SCAN_PERIOD = 300000L;

seem to be balanced fine. May be I missed something? Any ideas?....

One more thing. When in background I've noticed app makes scans each 10 seconds, putting messages to log

22643-23191/app.package W/BeaconAdapter﹕ No PK Range notifier set.  Ignoring ranging callback

Can we disable this?

**Comment by davidgyoung** [comment]
Yes, these are the battery saving settings applied by default with this library.  While any bluetooth scanning does use battery, these defaults drain the battery at a rate similar to cell standby.  This typically mans an extra 5% battery drain in a day's usage vs. not doing any bluetooth scanning.  

You can tune this for further battery savings by  lengthening the backgroundBetweenScanPeriod, but this will make it take more time to discover beacons when the app is in the background.  If you can live with detection times longer than 5 minutes, this may be an option for you.  For example, lengthening this to 10 minutes will cut your apps bluetooth battery usage in half.

**Comment by pnetesa** [comment]
Thanks for recommendations we'll try these params. Another thing I've noticed is ProximityKitRangeNotifier handler fires all the time each 10 seconds no matter what value I set in backgroundBetweenScanPeriod:

        proximityKitManager.setProximityKitRangeNotifier(new ProximityKitRangeNotifier() {
            @Override
            public void didRangeBeaconsInRegion(Collection<ProximityKitBeacon> proximityKitBeacons, ProximityKitBeaconRegion proximityKitBeaconRegion) {
                // Fires each 10 seconds
            }
        });

And the call involves not so lightweight operations, like firing intent BeaconIntentProcessor. As far as I can see range notifier always initiates in BeaconAdapter.updateRegions() and there is no way to disable it on start.

I disabled it in range notifier handler:

        proximityKitManager.setProximityKitRangeNotifier(new ProximityKitRangeNotifier() {
            @Override
            public void didRangeBeaconsInRegion(Collection<ProximityKitBeacon> proximityKitBeacons, ProximityKitBeaconRegion proximityKitBeaconRegion) {
                try {
                    proximityKitManager.getBeaconManager().stopRangingBeaconsInRegion(proximityKitBeaconRegion);
                } catch (RemoteException e) {
                    e.printStackTrace();
                }
            }
        });

I hope all the rest will work fine (including ProximityKitMonitorNotifier handlers).

**Comment by davidgyoung** [comment]
Pavel,

Are you sure you are not seeing pauses between ranging callbacks when your app is in the background?  You should see about 10 callbacks 1 second apart, then no callbacks for about 5 minutes.  If this is not what you see, then something may be wrong.  Please confirm.

If you do only get 10 callbacks every five minutes, then I doubt that disabling ranging will help with battery savings much, but it certainly won't hurt.

Thanks,
David

**Comment by pnetesa** [comment]
Hi David

Pauses between ranging callbacks do happen but they're short - 10 seconds in background, no matter what value I specify in ```setBackgroundBetweenScanPeriod()```.

As for me disabling ranging was helpful and now battery has longer life.

**Comment by davidgyoung** [comment]
Thanks for the update.  I am concerned that the lack of pauses between scan intervals indicates the library is not detecting the foreground/background state of your app, which can affect battery life.
