### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by n8fr8** [RadiusNetworks/proximitykit-android#6]
Distributing a binary compiled AAR on Github doesn't really make sense. Is this an open-source project, or just a developer library?

**Comment by csexton** [comment]
@n8fr8 this is not an open source library. It does take advantage of our open source [Android Beacon Library](https://github.com/AltBeacon/android-beacon-library/) internally, but Proximity Kit is a proprietary project. 

If you have any questions we are happy to discuss, feel free to drop us a note at support@radiusnetworks.com.
