### ISSUE TITLE
Only supported for Google Play Services Library versions 4.2.42 through < 9.0

### ISSUE THREAD

**Issue by Rohit-purpleDeck** [RadiusNetworks/proximitykit-android#7]
I am trying to use FCM with this library and fcm requires google play services version 9.0.0. I tried making changes to the sample app as well and upon changing the from the previous version of 6.5.87 the geofences don't work and I get the error mentioned in the title. Any help would be highly appreciated.

**Comment by Rohit-purpleDeck** [comment]
Thank you so much for you prompt response. Could you please give me an idea of when the next release would take place and also if there's a workaround for using FCM with ProximityKit which I can currently use. The beacons do work perfectly but the issue is only with Geofence.

**Comment by cupakromer** [comment]
We're currently evaluating how v9 affects our current code. We should have a better idea and timeline in the next day or two on when we can get a release ready.

**Comment by Rohit-purpleDeck** [comment]
Thank you. Looking forward to the next update.

**Comment by cupakromer** [comment]
We found a few things that are delaying the release. We're looking to push out a pre-release this Friday to help you move forward.

**Comment by cupakromer** [comment]
Sorry for the delay. We were putting it through some last minute testing. The pre-release version is now available with support for Google Play services 9.x: https://github.com/RadiusNetworks/proximitykit-android/releases/tag/0.12.0-pre

We plan on releasing the final GA version early September. Hopefully this pre-release will help you get moving forward for now.

**Comment by Rohit-purpleDeck** [comment]
Thank you so much. That'll help for now. Looking forward to the final version.

Get Outlook for Android<https://aka.ms/ghei36>



On Mon, Aug 22, 2016 at 11:36 AM -0400, "Aaron Kromer" <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry for the delay. We were putting it through some last minute testing. The pre-release version is now available with support for Google Play services 9.x: https://github.com/RadiusNetworks/proximitykit-android/releases/tag/0.12.0-pre

We plan on releasing the final GA version early September. Hopefully this pre-release will help you get moving forward for now.

-

**Comment by cupakromer** [comment]
@Rohit-purpleDeck I just wanted to let you know we've published the official release with Google Play v9 support: https://github.com/RadiusNetworks/proximitykit-android/releases/tag/0.12.0

**Comment by Rohit-purpleDeck** [comment]
Thank you so much.

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Sep 8, 2016 at 10:50 AM -0400, "Aaron Kromer" <notifications@github.com<mailto:notifications@github.com>> wrote:


@Rohit-purpleDeck<https://github.com/Rohit-purpleDeck> I just wanted to let you know we've published the official release with Google Play v9 support: https://github.com/RadiusNetworks/proximitykit-android/releases/tag/0.12.0

-
