### ISSUE TITLE
Proximity Kit is not working well in background. 

### ISSUE THREAD

**Issue by iabdelgawaad** [RadiusNetworks/proximitykit-android#8]
Hi,

Really, It's a great library for detecting beacons I ever used very easy and straight forward.

But I've an issue when app is in background application not detect beacons well than foreground. It's working randomly. 

I'm working on latest version of proximity-kit: com.radiusnetworks:proximitykit-android-0.12.3@aar. 

Also, I'm not doing my implementation in the application class I actually start service that can make all beacons functions. Is this a problem to isolate my beacons code outside application class. What do you think? 

Please help ASAP. 

Thanks in advance!

**Comment by cupakromer** [comment]
This should now be resolved in the latest release: https://github.com/RadiusNetworks/proximitykit-android/releases/tag/0.13.0
